set modeline
set background=dark
set ts=4
set sts=4
set expandtab

set backupdir-=.
set backupdir^=~/tmp,/tmp
set backup

"vimcast.org episode 1:
set listchars=tab:▸\ ,eol:¬
"set list
:nmap <leader>l :set list!<CR>

":help listchars
:highlight NonText      guifg=#4a4a59
:highlight SpecialKey   guifg=#4a4a59

"vimcast.org episode 3
" Only do this part when compiled with support for autocommands
if has("autocmd")
  " Enable file type detection
  filetype on

  " Syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

  " Customisations based on house-style (arbitrary)
  autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab

  " Treat .rss files as XML
  autocmd BufNewFile,BufRead *.rss setfiletype xml
endif


" :help search-commands
set hlsearch
